//Colors:
#define COLOR_RED 			(0x6C1D1DFF)

#define COLOR_GREEN 		(0x5B9460FF)
#define COLOR_DARKGREEN 	(0x5B9460FF)

#define COLOR_CREDITS       (0xf8b56eFF)

#define COLOR_SERVER		(0xdcdd8aFF)
#define COLOR_GAMES         (0xb6b9e1FF)
#define COLOR_HEADER		(0x90D7F0FF)

#define COLOR_YELLOW 		(0xFFFF00FF)

#define COLOR_PHONE         (0xac90c7FF)
#define COLOR_JOBS          (0x6fa8dcFF)
#define COLOR_VEHICLE       (0xbab8daFF)
#define COLOR_FISHING       (0xaff0f7FF)
#define COLOR_INVENTORY     (0xE5ECD0FF)
#define COLOR_FACTION       (0xd1f8ccFF)
#define COLOR_STORE         (0xaa9b83FF)
#define COLOR_RELATIONS     (0xe4b4cbFF)
#define COLOR_WEAPONS       (0x16797eFF)
#define COLOR_MONEY         (0xD4EDD7FF)
#define COLOR_ADVERTISE     (0xd4f4deFF)

#define COLOR_GRAD1			(0xCCE6E6FF)
#define COLOR_GRAD2			(0xE2FFFFFF)

#define COLOR_WHITE 		(0xFFFFFFFF)
#define COLOR_GREY 			(0xAFAFAFFF)

#define COLOR_EMOTE			(0xC2A2DAAA)
#define COLOR_EMOTE_LOW     (0xA486BAAA)
#define COLOR_REPORT 		(0xFFFF91FF)

#define COLOR_FADE1 		(0xE6E6E6E6)
#define COLOR_FADE2 		(0xC8C8C8C8)
#define COLOR_FADE3 		(0xAAAAAAAA)
#define COLOR_FADE4 		(0x8C8C8C8C)
#define COLOR_FADE5 		(0x6E6E6E6E)

#define COLOR_COP 			(0x8D8DFFFF)
#define COLOR_MEDIC         (0xDFA0C1FF)
#define COLOR_DEPT 			(0xF07A7AFF)

#define COLOR_SAMP			(0xADC3E7FF)

#define COLOR_RADIO			(0xFFEC8BFF)
#define COLOR_RADIOEX 		(0xB5AF8FFF)

#define COLOR_PMRECEIVED 	(0xFFDC18FF)
#define COLOR_PMSENT 		(0xEEE854FF)

#define COLOR_CYAN 			(0x00FFFFFF)
#define COLOR_PINK			(0xFF8282FF)
#define COLOR_PURPLE 		(0x6613BFFF)
#define COLOR_POINT 		(0xb6d9e1FF)
#define COLOR_OOC         	(0xAAC4E5FF)
#define COLOR_DEFAULT 		(0xC8C8C8C8)


