//SALARY JOBS
#define GARBAGEMAN_SALARY       5
#define SWEEPER_SALARY          4
#define BUSDRIVER_SALARY        10
#define DOCKWORKER_SALARY       15
#define LUMBERJACK_SALARY       25

//FISH PRICE
#define COD_PRICE          1
#define CARP_PRICE          2
#define SALMON_PRICE          3
#define CATFISH_PRICE          4
#define HERRING_PRICE          4

//FSTORAGE
#define WEAPON_COLT         2000
#define WEAPON_SLC          2500
#define WEAPON_UZIS         4000
#define WEAPON_DEAGLES      5000
#define WEAPON_SHOTGUNS     3000
#define PMARIJUANA          200
#define PCOCAINE            250
#define PHEROIN             300
#define A9MM                100
#define A9X19MM             250

//CARGO PRICE
#define PRICE_FISH 5
#define PRICE_FABRIC 5
#define PRICE_STEEL 6
#define PRICE_WOODS 6

#define PRICE_FOODS 6
#define PRICE_CLOTHES 6
#define PRICE_APPLIANCES 7
