//SALARY JOBS
#define TRASHMASTER_SALARY      1
#define DOCKWORKER_SALARY       30
#define FISHING_SALARY          10
#define BURGLARY_SALARY         400

//FSTORAGE
#define GLOCK19         3000
#define GLOCK17         3500
#define GLOCKP80        4000
#define MAC11           4000
#define MAC10           4500
#define SOCIMIT821      4500
#define PMARIJUANA       1000
#define PCOCAINE         1750
#define PHEROIN          1250
#define A9MM            200
#define A9X19MM         200

//CARGO PRICE
#define PRICE_PRODUCTS 5
