//FISH PRICE
#define COD_PRICE          5.0
#define CARP_PRICE          5.3
#define SALMON_PRICE          5.5
#define CATFISH_PRICE          6.0
#define HERRING_PRICE          6.0

//FSTORAGE
#define WEAPON_COLT         2000
#define WEAPON_SLC          2500
#define WEAPON_UZIS         4000
#define WEAPON_DEAGLES      5000
#define WEAPON_SHOTGUNS     3000
#define PMARIJUANA          200
#define PCOCAINE            250
#define PHEROIN             300
#define A9MM                100
#define A9X19MM             250
