//Faction
#define FACTION_TYPE_ILLEGAL (1)
#define FACTION_TYPE_POLICE (2)
#define FACTION_TYPE_MEDICAL (3)

//Property types:
#define PROPERTY_TYPE_HOUSE (1)
#define PROPERTY_TYPE_APTCOMPLEX (2)
#define PROPERTY_TYPE_HIGHHOUSE (3)

//Business types:
#define BUSINESS_TYPE_DINNER (1) // Foods
#define BUSINESS_TYPE_BAR (2) // Foods
#define BUSINESS_TYPE_ACID (3)
#define BUSINESS_TYPE_GUNSTORE (4)
#define BUSINESS_TYPE_CLUB (5) // Foods
#define BUSINESS_TYPE_BANK (6)
#define BUSINESS_TYPE_GENERAL (7) // Appliances
#define BUSINESS_TYPE_CLOTHES (8) // Clothes
#define BUSINESS_TYPE_DEALERSHIP (9)
#define BUSINESS_TYPE_DMV (10) 
#define BUSINESS_TYPE_HAIRCUT (11)
#define BUSINESS_TYPE_RENT (12) 
#define BUSINESS_TYPE_GYM (13)


//Player states:
#define PLAYER_STATE_ALIVE (1)
#define PLAYER_STATE_WOUNDED (2)
#define PLAYER_STATE_DEAD (3)

//Body parts:
#define BODY_PART_CHEST	(3)
#define BODY_PART_GROIN (4)
#define BODY_PART_LEFT_ARM (5)
#define BODY_PART_RIGHT_ARM (6)
#define BODY_PART_LEFT_LEG (7)
#define BODY_PART_RIGHT_LEG (8)
#define BODY_PART_HEAD (9)

//Spawn points:
#define SPAWN_POINT_HOODRATS (0)
#define SPAWN_POINT_LAST (1)
#define SPAWN_POINT_FACTION (2)

//Robbery
#define TYPE_SUCCESS        (0)
#define TYPE_FAILED         (1)
#define TYPE_UNFINISHED     (2)

//fISHING
#define CHECKPOINT_NONE 			0
#define CHECKPOINT_UNLOADFISHING	7
#define CHECKPOINT_GOFISHING 		8