/*

==================================================================================================
   ______                _   _   _____                           _         _____  _____   _____ 
  |  ____|              | \ | | |  __ \                         | |       |  __ \|  __ \ / ____|
  | |__ ___  __ _ _ __  |  \| | | |__) |___  ___ _ __   ___  ___| |_      | |__) | |__) | |  __ 
  |  __/ _ \/ _` | '__| | . ` | |  _  // _ \/ __| '_ \ / _ \/ __| __|     |  _  /|  ___/| | |_ |
  | | |  __/ (_| | |    | |\  | | | \ \  __/\__ \ |_) |  __/ (__| |_   _  | | \ \| |    | |__| |
  |_|  \___|\__,_|_|    |_| \_| |_|  \_\___||___/ .__/ \___|\___|\__| (_) |_|  \_\_|     \_____|
                                                | |                                             
                                                |_|  

  #Thanks to Radeetz for making this script.
  #Special thanks to GTA-Chronicles / SP-RP / SOLS for credits the Environment.
================================================================================================== 

| Changelogs |

[+]
    Added /creategun & /createammo in warehouses using materials. -
    Added properties type warehouses [Acid lab & Storehouse]. -
    Added Materials items inventory. -
    Added lumberjack jobs.
[x]
    Fixed database from factions skin. -
[*]
    Improvement & Fixed other Bugs.
    Improvement Drugs Production scripts.
    Rewrote Spraycan / Spraytags script. -
    Rewrote business & relations script. -
    Rewrote GYM script.
[-]

*/